import SwiftUI

// Generated by Supernova - do not modify manually
public extension Text {

    // heading

    func textStyleHeadingHeading1() -> some View {
        return self
            .font(Font.custom("Proxima Nova-600", size: 16))
    }

    func textStyleHeadingHeading2() -> some View {
        return self
            .font(Font.custom("Proxima Nova-600", size: 19))
    }

    func textStyleHeadingHeading3() -> some View {
        return self
            .font(Font.custom("Proxima Nova-700", size: 23))
    }

    func textStyleHeadingHeading4() -> some View {
        return self
            .font(Font.custom("Proxima Nova-700", size: 28))
    }

    func textStyleHeadingHeading5() -> some View {
        return self
            .font(Font.custom("Proxima Nova-700", size: 33))
    }

    func textStyleHeadingHeading6() -> some View {
        return self
            .font(Font.custom("Proxima Nova-700", size: 40))
    }

    // body

    func textStyleBodyBody1() -> some View {
        return self
            .font(Font.custom("Proxima Nova-400", size: 12))
    }

    func textStyleBodyBody1Bold() -> some View {
        return self
            .font(Font.custom("Proxima Nova-700", size: 12))
    }

    func textStyleBodyBody2() -> some View {
        return self
            .font(Font.custom("Proxima Nova-400", size: 14))
    }

    func textStyleBodyBody2Bold() -> some View {
        return self
            .font(Font.custom("Proxima Nova-700", size: 14))
    }

    func textStyleBodyBody3() -> some View {
        return self
            .font(Font.custom("Proxima Nova-400", size: 16))
    }

    func textStyleBodyBody3Bold() -> some View {
        return self
            .font(Font.custom("Proxima Nova-700", size: 16))
    }

    // label

    func textStyleLabelLabel1() -> some View {
        return self
            .font(Font.custom("Proxima Nova-500", size: 12))
    }

    func textStyleLabelLabel1Bold() -> some View {
        return self
            .font(Font.custom("Proxima Nova-700", size: 12))
    }

    func textStyleLabelLabel2() -> some View {
        return self
            .font(Font.custom("Proxima Nova-500", size: 14))
    }

    func textStyleLabelLabel2Bold() -> some View {
        return self
            .font(Font.custom("Proxima Nova-700", size: 14))
    }

    func textStyleLabelLabel2Caps() -> some View {
        return self
            .font(Font.custom("Proxima Nova-700", size: 14))
            .textCase(.uppercase) 
    }

    func textStyleLabelLabel3() -> some View {
        return self
            .font(Font.custom("Proxima Nova-500", size: 16))
    }

    func textStyleLabelLabel3Bold() -> some View {
        return self
            .font(Font.custom("Proxima Nova-700", size: 16))
    }

    func textStyleLabelLabel3Caps() -> some View {
        return self
            .font(Font.custom("Proxima Nova-700", size: 16))
            .textCase(.uppercase) 
    }

    // tabular

    func textStyleTabularTabular1() -> some View {
        return self
            .font(Font.custom("Proxima Nova-500", size: 12))
    }

    func textStyleTabularTabular2() -> some View {
        return self
            .font(Font.custom("Proxima Nova-500", size: 14))
    }

    func textStyleTabularTabular3() -> some View {
        return self
            .font(Font.custom("Proxima Nova-500", size: 16))
    }
}
