import SwiftUI

// Generated by Supernova - do not modify manually
public struct AppMeasures {

    // Dimension

    // space
    public static let dimensionspaceBase = 8 
    public static let dimensionspaceSpace500 = 40 
    public static let dimensionspaceSpace400 = 32 
    public static let dimensionspaceSpace300 = 24 
    public static let dimensionspaceSpace200 = 16 
    public static let dimensionspaceSpace150 = 12 
    public static let dimensionspaceSpace100 = 8 
    public static let dimensionspaceSpace75 = 6 
    public static let dimensionspaceSpace50 = 4 
    public static let dimensionspaceSpace25 = 2 
    public static let dimensionspaceSpace0 = 0 

    // radius
    public static let dimensionradiusRadiusBase = 8 
    public static let dimensionradiusRadius0 = 0 
    public static let dimensionradiusRadius50 = 4 
    public static let dimensionradiusRadius100 = 8 
    public static let dimensionradiusRadius150 = 12 
    public static let dimensionradiusRadius300 = 24 
    public static let dimensionradiusRadiusMax = 8000 
}